In [1]:
import pandas as pd
from pathlib import Path

In [5]:
file_path = Path("../input/Y9999_20260813.xlsx")

df = pd.read_excel(
    file_path,
    header=1
)

df.head()

,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,流通在外股數(千股),...,現金股利率,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別
0,2026/08/12,45175.70,45529.48,45175.70,45518.07,9972596,892659784,0.8806,0.6156,798784627,...,1.6311,397.35,0.7841,NaN,NaN,NaN,NaN,NaN,NaN,TSE
1,2026/08/11,44883.90,45195.41,44652.06,45120.72,9740372,902052207,0.4273,0.6422,798787184,...,1.6455,191.96,1.2094,NaN,NaN,NaN,NaN,NaN,NaN,TSE
2,2026/08/10,44540.71,45219.40,44540.71,44928.76,10238975,880440723,1.5892,0.6202,798051817,...,1.6253,702.85,1.5346,NaN,NaN,NaN,NaN,NaN,NaN,TSE
3,2026/08/07,44450.19,44827.13,43941.56,44225.91,9376069,850815189,-0.3847,0.5600,798047934,...,1.6513,-170.79,1.9947,NaN,NaN,NaN,NaN,NaN,NaN,TSE
4,2026/08/06,44487.94,44601.24,44024.32,44396.70,10650583,974054973,-0.4817,0.6247,798048468,...,1.6451,-214.90,1.2932,NaN,NaN,NaN,NaN,NaN,NaN,TSE

確認欄位名稱

In [6]:
df.columns.tolist()

['年月日',
 '開盤價(元)',
 '最高價(元)',
 '最低價(元)',
 '收盤價(元)',
 '成交量(千股)',
 '成交值(千元)',
 '報酬率％',
 '週轉率％',
 '流通在外股數(千股)',
 '市值(百萬元)',
 '最後揭示買價',
 '最後揭示賣價',
 '報酬率-Ln',
 '市值比重％',
 '成交值比重％',
 '成交筆數(筆)',
 '本益比-TSE',
 '本益比-TEJ',
 '股價淨值比-TSE',
 '股價淨值比-TEJ',
 '漲跌停',
 '股價營收比-TEJ',
 '股利殖利率-TSE',
 '現金股利率',
 '股價漲跌(元)',
 '高低價差%',
 '次日開盤參考價',
 '次日漲停價',
 '次日跌停價',
 '注意股票(A)',
 '處置股票(D)',
 '全額交割(Y)',
 '市場別']

確定格式

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6733 entries, 0 to 6732
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   年月日         6733 non-null   str
 1   開盤價(元)      6733 non-null   float64
 2   最高價(元)      6733 non-null   float64
 3   最低價(元)      6733 non-null   float64
 4   收盤價(元)      6733 non-null   float64
 5   成交量(千股)     6733 non-null   int64
 6   成交值(千元)     6733 non-null   int64
 7   報酬率％        6733 non-null   float64
 8   週轉率％        6733 non-null   float64
 9   流通在外股數(千股)  6733 non-null   int64
 10  市值(百萬元)     6733 non-null   int64
 11  最後揭示買價      0 non-null      float64
 12  最後揭示賣價      0 non-null      float64
 13  報酬率-Ln      6733 non-null   float64
 14  市值比重％       6733 non-null   int64
 15  成交值比重％      6733 non-null   int64
 16  成交筆數(筆)     6733 non-null   int64
 17  本益比-TSE     0 non-null      float64
 18  本益比-TEJ     6733 non-null   float64
 19  股價淨值比-TSE   0 non-null      float64
 20  股價淨值比-TEJ   6733 non-null   float64
 21  漲跌停         0 non-null      float64
 22  股價營收比-TEJ   6733 non-null   float64
 23  股利殖利率-TSE   0 non-null      float64
 24  現金股利率       6733 non-null   float64
 25  股價漲跌(元)     6733 non-null   float64
 26  高低價差%       6733 non-null   float64
 27  次日開盤參考價     0 non-null      float64
 28  次日漲停價       0 non-null      float64
 29  次日跌停價       0 non-null      float64
 30  注意股票(A)     0 non-null      float64
 31  處置股票(D)     0 non-null      float64
 32  全額交割(Y)     0 non-null      float64
 33  市場別         6733 non-null   str
dtypes: float64(25), int64(7), str(2)
memory usage: 1.7 MB

確定筆數

In [8]:
df.shape

(6733, 34)

看尾部

In [9]:
df.tail()

,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,流通在外股數(千股),...,現金股利率,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別
6728,1999/06/05,7649.47,7684.85,7618.80,7639.30,2943000,151565000,0.6437,1.0624,272454220,...,0.7034,48.86,0.8702,NaN,NaN,NaN,NaN,NaN,NaN,TSE
6729,1999/06/04,7613.15,7628.14,7576.98,7590.44,2686000,133137000,0.2315,0.9720,272421515,...,0.7074,17.53,0.6756,NaN,NaN,NaN,NaN,NaN,NaN,TSE
6730,1999/06/03,7552.36,7604.51,7552.36,7572.91,3231000,155821000,1.1335,1.1629,272421515,...,0.6747,84.88,0.6964,NaN,NaN,NaN,NaN,NaN,NaN,TSE
6731,1999/06/02,7426.06,7493.68,7426.06,7488.03,2550000,119107000,1.2221,0.9121,272421515,...,0.7064,90.41,0.9141,NaN,NaN,NaN,NaN,NaN,NaN,TSE
6732,1999/06/01,7324.42,7397.62,7313.12,7397.62,1831000,83584000,1.1078,0.6548,272421515,...,0.7155,81.05,1.1549,NaN,NaN,NaN,NaN,NaN,NaN,TSE

格式總確認

In [10]:
df.head()
df.columns.tolist()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6733 entries, 0 to 6732
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   年月日         6733 non-null   str
 1   開盤價(元)      6733 non-null   float64
 2   最高價(元)      6733 non-null   float64
 3   最低價(元)      6733 non-null   float64
 4   收盤價(元)      6733 non-null   float64
 5   成交量(千股)     6733 non-null   int64
 6   成交值(千元)     6733 non-null   int64
 7   報酬率％        6733 non-null   float64
 8   週轉率％        6733 non-null   float64
 9   流通在外股數(千股)  6733 non-null   int64
 10  市值(百萬元)     6733 non-null   int64
 11  最後揭示買價      0 non-null      float64
 12  最後揭示賣價      0 non-null      float64
 13  報酬率-Ln      6733 non-null   float64
 14  市值比重％       6733 non-null   int64
 15  成交值比重％      6733 non-null   int64
 16  成交筆數(筆)     6733 non-null   int64
 17  本益比-TSE     0 non-null      float64
 18  本益比-TEJ     6733 non-null   float64
 19  股價淨值比-TSE   0 non-null      float64
 20  股價淨值比-TEJ   6733 non-null   float64
 21  漲跌停         0 non-null      float64
 22  股價營收比-TEJ   6733 non-null   float64
 23  股利殖利率-TSE   0 non-null      float64
 24  現金股利率       6733 non-null   float64
 25  股價漲跌(元)     6733 non-null   float64
 26  高低價差%       6733 non-null   float64
 27  次日開盤參考價     0 non-null      float64
 28  次日漲停價       0 non-null      float64
 29  次日跌停價       0 non-null      float64
 30  注意股票(A)     0 non-null      float64
 31  處置股票(D)     0 non-null      float64
 32  全額交割(Y)     0 non-null      float64
 33  市場別         6733 non-null   str
dtypes: float64(25), int64(7), str(2)
memory usage: 1.7 MB

轉換日期

In [11]:
df["年月日"] = pd.to_datetime(
    df["年月日"],
    format="%Y/%m/%d"
)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6733 entries, 0 to 6732
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   年月日         6733 non-null   datetime64[us]
 1   開盤價(元)      6733 non-null   float64
 2   最高價(元)      6733 non-null   float64
 3   最低價(元)      6733 non-null   float64
 4   收盤價(元)      6733 non-null   float64
 5   成交量(千股)     6733 non-null   int64
 6   成交值(千元)     6733 non-null   int64
 7   報酬率％        6733 non-null   float64
 8   週轉率％        6733 non-null   float64
 9   流通在外股數(千股)  6733 non-null   int64
 10  市值(百萬元)     6733 non-null   int64
 11  最後揭示買價      0 non-null      float64
 12  最後揭示賣價      0 non-null      float64
 13  報酬率-Ln      6733 non-null   float64
 14  市值比重％       6733 non-null   int64
 15  成交值比重％      6733 non-null   int64
 16  成交筆數(筆)     6733 non-null   int64
 17  本益比-TSE     0 non-null      float64
 18  本益比-TEJ     6733 non-null   float64
 19  股價淨值比-TSE   0 non-null      float64
 20  股價淨值比-TEJ   6733 non-null   float64
 21  漲跌停         0 non-null      float64
 22  股價營收比-TEJ   6733 non-null   float64
 23  股利殖利率-TSE   0 non-null      float64
 24  現金股利率       6733 non-null   float64
 25  股價漲跌(元)     6733 non-null   float64
 26  高低價差%       6733 non-null   float64
 27  次日開盤參考價     0 non-null      float64
 28  次日漲停價       0 non-null      float64
 29  次日跌停價       0 non-null      float64
 30  注意股票(A)     0 non-null      float64
 31  處置股票(D)     0 non-null      float64
 32  全額交割(Y)     0 non-null      float64
 33  市場別         6733 non-null   str
dtypes: datetime64[us](1), float64(25), int64(7), str(1)
memory usage: 1.7 MB

確認日期

In [21]:
df["年月日"].min(), df["年月日"].max()

(Timestamp('1999-06-01 00:00:00'), Timestamp('2026-08-12 00:00:00'))

In [20]:
df["年月日"].duplicated().sum()

np.int64(0)

確認市場別

In [15]:
df["市場別"].value_counts(dropna=False)

np.int64(0)

建立表格

In [22]:
column_map = {
    "年月日": "trade_date",
    "開盤價(元)": "open_price",
    "最高價(元)": "high_price",
    "最低價(元)": "low_price",
    "收盤價(元)": "close_price",
    "成交量(千股)": "volume_thousand_shares",
    "成交值(千元)": "turnover_value_thousand",
    "報酬率％": "return_pct",
    "週轉率％": "turnover_rate_pct",
    "流通在外股數(千股)": "shares_outstanding_thousand",
    "市值(百萬元)": "market_cap_million",
    "最後揭示買價": "last_bid_price",
    "最後揭示賣價": "last_ask_price",
    "報酬率-Ln": "log_return",
    "市值比重％": "market_cap_weight_pct",
    "成交值比重％": "turnover_value_weight_pct",
    "成交筆數(筆)": "trade_count",
    "本益比-TSE": "pe_tse",
    "本益比-TEJ": "pe_tej",
    "股價淨值比-TSE": "pb_tse",
    "股價淨值比-TEJ": "pb_tej",
    "漲跌停": "price_limit_status",
    "股價營收比-TEJ": "ps_tej",
    "股利殖利率-TSE": "dividend_yield_tse",
    "現金股利率": "cash_dividend_yield",
    "股價漲跌(元)": "price_change",
    "高低價差%": "high_low_spread_pct",
    "次日開盤參考價": "next_open_reference_price",
    "次日漲停價": "next_limit_up_price",
    "次日跌停價": "next_limit_down_price",
    "注意股票(A)": "is_attention",
    "處置股票(D)": "is_disposition",
    "全額交割(Y)": "is_full_delivery",
    "市場別": "market"
}

df = df.rename(columns=column_map)

In [23]:
df.columns.tolist()

['trade_date',
 'open_price',
 'high_price',
 'low_price',
 'close_price',
 'volume_thousand_shares',
 'turnover_value_thousand',
 'return_pct',
 'turnover_rate_pct',
 'shares_outstanding_thousand',
 'market_cap_million',
 'last_bid_price',
 'last_ask_price',
 'log_return',
 'market_cap_weight_pct',
 'turnover_value_weight_pct',
 'trade_count',
 'pe_tse',
 'pe_tej',
 'pb_tse',
 'pb_tej',
 'price_limit_status',
 'ps_tej',
 'dividend_yield_tse',
 'cash_dividend_yield',
 'price_change',
 'high_low_spread_pct',
 'next_open_reference_price',
 'next_limit_up_price',
 'next_limit_down_price',
 'is_attention',
 'is_disposition',
 'is_full_delivery',
 'market']

In [24]:
df.dtypes

trade_date                     datetime64[us]
open_price                            float64
high_price                            float64
low_price                             float64
close_price                           float64
volume_thousand_shares                  int64
turnover_value_thousand                 int64
return_pct                            float64
turnover_rate_pct                     float64
shares_outstanding_thousand             int64
market_cap_million                      int64
last_bid_price                        float64
last_ask_price                        float64
log_return                            float64
market_cap_weight_pct                   int64
turnover_value_weight_pct               int64
trade_count                             int64
pe_tse                                float64
pe_tej                                float64
pb_tse                                float64
pb_tej                                float64
price_limit_status                    float64
ps_tej                                float64
dividend_yield_tse                    float64
cash_dividend_yield                   float64
price_change                          float64
high_low_spread_pct                   float64
next_open_reference_price             float64
next_limit_up_price                   float64
next_limit_down_price                 float64
is_attention                          float64
is_disposition                        float64
is_full_delivery                      float64
market                                    str
dtype: object

In [25]:
df.isna().sum().sort_values(ascending=False)

pe_tse                         6733
last_ask_price                 6733
next_open_reference_price      6733
next_limit_up_price            6733
last_bid_price                 6733
is_attention                   6733
is_full_delivery               6733
dividend_yield_tse             6733
price_limit_status             6733
is_disposition                 6733
next_limit_down_price          6733
pb_tse                         6733
open_price                        0
trade_date                        0
turnover_value_thousand           0
low_price                         0
close_price                       0
high_price                        0
trade_count                       0
turnover_value_weight_pct         0
market_cap_weight_pct             0
log_return                        0
market_cap_million                0
return_pct                        0
turnover_rate_pct                 0
shares_outstanding_thousand       0
volume_thousand_shares            0
price_change                      0
ps_tej                            0
pb_tej                            0
pe_tej                            0
cash_dividend_yield               0
high_low_spread_pct               0
market                            0
dtype: int64

In [26]:
df["trade_date"].dtype

dtype('<M8[us]')